/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "diutyuulfulleqfmjlxp"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpdXR5dXVsZnVsbGVxZm1qbHhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU5MTIwODgsImV4cCI6MjA4MTQ4ODA4OH0.y-JROlzATycLHcEyqOppWe1HNi-nQaV6kBg7FAa1F6Y"