tunnel: 1ca34d31-ae16-42e8-ba67-75d95a8fb2f8
credentials-file: C:\Users\Admin\.cloudflared\1ca34d31-ae16-42e8-ba67-75d95a8fb2f8.json
ingress:
  - hostname: flightpoints.uk
    service: http://127.0.0.1:3001
  - hostname: api.flightpoints.uk
    service: http://127.0.0.1:3001
  - hostname: db.flightpoints.uk
    service: tcp://127.0.0.1:5432
  - hostname: panel.flightpoints.uk
    service: http://127.0.0.1:4000
  - service: http_status:404
